apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nfs-server-alpine
    app.kubernetes.io/component: nfs-server-alpine
    app.kubernetes.io/instance: nfs-server-alpine
  name: nfs-server-alpine
spec:
  replicas: 1
  selector:
    matchLabels:
      deployment: nfs-server-alpine
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        deployment: nfs-server-alpine
    spec:
      containers:
      - env:
        - name: SHARED_DIRECTORY
          value: /nfsshare
        image: itsthenetwork/nfs-server-alpine@sha256:7fa99ae65c23c5af87dd4300e543a86b119ed15ba61422444207efc7abd0ba20
        imagePullPolicy: IfNotPresent
        name: nfs-server-alpine
        lifecycle:
          postStart:
            exec:
              command: 
               - "/bin/sh"
               - "-c"
               - >
                 for dir in $(seq 100); do mkdir $SHARED_DIRECTORY/pv$dir && chmod 777 $SHARED_DIRECTORY/pv$dir; done 
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /nfsshare
          name: volume
      volumes:
      - emptyDir: {}
        name: volume